# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Log-Syslog-Fast
version:      0.35
version_from: lib/Log/Syslog/Fast.pm
installdirs:  site
requires:
resources:
  repository: http://github.com/athomason/Log-Syslog-Fast

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
